apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: ngin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngin
  template:
    metadata:
      labels:
        app: ngin
    spec:
      containers:
      - name: boxone
        image: nginx:1.14.2
        ports:
        - containerPort: 80
