### 1. Database Credentials and Storage Configuration ###

apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  # Base64 encoded values. 
  # 'rootpassword' -> cm9vdHBhc3N3b3Jk
  # 'app-db-user-pass' -> YXBwLWRiLXVzZXItcGFzcw==
  # 'https://slack.com...' -> YOUR_BASE64_WEBHOOK_URL_HERE
  mysql-root-password: cm9vdHBhc3N3b3Jk
  mysql-password: YXBwLWRiLXVzZXItcGFzcw==
  webhook-url: YOUR_BASE64_WEBHOOK_URL_HERE

