---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-dbcreds
  namespace: default
spec:
  encryptedData:
    password: AgCjOk0jIoa+huB33EtJVJ9z+F4KxqC0G+jjk3YJZVfv91oHsJ7rMqBjOABCn9vDDF3QngGbhRpT2IpSfZI3UzeQXXYUhdy+JsshRtS/Gtbh3cntyuDZ++cvz/XlOzmEvbdWGzgiXN+Rl5zALmchzABHSfD0ZlKEUPae2uUA2Eu6zgm/SF63o18uIoIHY3MPBKJ6OOekhf3i3DVsh1okZYESK1plUjXIhvgBYDgHgACTn9q0mtyAlAUpV7y+wH/bQfDhYGwLrQLW0Z6gwDfGquy1GgdPZkiCcVg2QGvt/cHLGCKktx1z4KXO2yVTliK+SVjMmO4nIp4+CcJWBnj6yMNs10p+pHjI6wcy8NLi3c0w5BRYQEBsIhn2nDtwbQAwcQnap9EprWYdiXcvxmZG+Vv8uZ8Bdxr5joarUS291X/Gp1iwL4cdseIzoV8SxZ2NMvPjdHCuG/ZipJtgb4sbytq9DqZZ13HkwOmje4PC4zULlaRKVGEK77TeP3FM82gEIEsY8gyKO8v04vj0W0GKqln1kjQ3KQ6kobEGLXXLRDJxVERwFzRrvP65SssRWTlGBBHiNzcKrx4gnlPTNvqLtpZKxp6jpIFSC+k8pcPXNhypM+25gOOrKXOTW+fbtEuPUDGIOuOy1YdUOitrzzZ1MKgHG1Ozk/xyOfEdek6baRwx+JIXMGMMU2EAYzoVrAF06QB1GY40rNpMVezESkj23tQQLg==
    username: AgClVQd+MOJU8M7ul5e5P1N3HD0LoKBx4QnajVQmQWSzC/h5XuXAcuyKER/aQoWa4bmMywW9Re3qN1QkCQ4FLZ3KTFfWjM07x/PKz3N3xILTLLPxXJQ9itwJojW7Ub1Q6x/o9i+smSlQAq5kptq2tsCWNjnhUMdScRWnjS4wd6vv+rWpUlWUiPTx4thF6tknyVHmvi4cv/SJB9qn69NpwXGvD2Sng7gud8u58VHwmbjop2MFon/GZNGVa6DLEiGTbuveHRyrQGc9hg1H5Nu3Rz3bIKhg5fq/WLUhXzdrgYb1U9s09Ac9P+lcu9ibx7XNGQo9PcZzb9bUzQvTtR1cXUh74JtMaLDs+QNDrer+lx9pU6MIh5/EXMOHPSXxfT3cbB+uxTdY5OVT1sP9D05rtdTzBpKeZkQfhWWWtKDD0SqyIlNHVSf38rWHRPofEjvaqKEVVOTicbG8O5DXuB3XLdCJrNLTkEni3qKeweqd1rsGMXDN6LB2ipdSV1mFV1CqoNRngAJKy+hfR7/y6jWKjEzrJXPpSyiekxr4H5S0T0g9wXtRv8MCQh1XLRH/uXOz2Fy1hUMcnjk7OUprgFKUYHDJrKQytCRJ6RlP5la+f7lgVPnpude3zojQvPwJgbzTsMx4SesvAL1sx1/Cny2kSdSvcPSBCCMPaecda6aAicnX4Hv6OWCV4asH/RkxTcLdQcowKKXQSQ==
  template:
    metadata:
      creationTimestamp: null
      name: my-dbcreds
      namespace: default
